apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: showmethemoney
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      nodeSelector:
        workload: backend-db
      containers:
        - name: backend
          image: showmethemoney-backend:v1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: showmethemoney-config
            - secretRef:
                name: showmethemoney-secret
          readinessProbe:
            httpGet:
              path: /api/health
              port: 8080
            initialDelaySeconds: 25
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/health
              port: 8080
            initialDelaySeconds: 45
            periodSeconds: 20
