apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-data
  namespace: showmethemoney
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: showmethemoney-local
  resources:
    requests:
      storage: 10Gi
