apiVersion: v1
kind: ConfigMap
metadata:
  name: showmethemoney-config
  namespace: showmethemoney
data:
  SPRING_PROFILES_ACTIVE: "k8s"
  DB_URL: "jdbc:mysql://mysql:3306/showmethemoney?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8"
  JWT_EXPIRATION: "3600"
