apiVersion: v1
kind: Secret
metadata:
  name: showmethemoney-secret
  namespace: showmethemoney
type: Opaque
stringData:
  DB_USERNAME: "showmethemoney"
  DB_PASSWORD: "change-me"
  MYSQL_ROOT_PASSWORD: "change-me-root"
  JWT_SECRET: "change-me-change-me-change-me-change-me"
